spring.application.name=peru
# Configuraci\u00f3n de la conexi\u00f3n a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/BD_MGKS?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuraci\u00f3n de Hibernate / JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuraci\u00f3n del Token JWT (La firma secreta debe tener m\u00ednimo 32 caracteres)
jwt.secret=EstaEsUnaClaveSecretaSuperSeguraYFirmeParaElSistemaMGKS2026
jwt.expiration=86400000

# Configuraci\u00f3n del servidor de desarrollo
app.cors.allowed-origin=http://localhost:4200